---
- hosts: all
  tasks:
    - name: create users account
      src: https://github.com/yomesky2000/yommylesson/user.sh
      
    - name: create files
      file: path=/tmp/ginger-sh
            owner=root
            group=root
            mode=0655
            state=present
