---
- hosts: suf 
  tasks:
    - name: create directory
      file: path=/ven state=directory owner=root group=root mode=0755
    - name: clone repo from Github
     # git: repo=https://github.com/yomesky2000/yommylesson.git dest=/mnt/ force=yes
      shell: cd /ven && wget https://github.com/yomesky2000/yommylesson/raw/master/user.sh
    - name: create a file
      file: path=/ven/user.sh  owner=root group=root mode=0755
    - name: Run the script from the location 
      shell: cd /ven && bash user.sh
